Repository speedshell/minishell, pull requests merged in 2022-12, with the labels that each got.

#25 Builtin Env - fixing builting invocation
  Makefile
  includes/minishell.h
  src/build_env.c
  src/command_executor.c
  src/command_loader.c
  src/env.c
  src/main.c
  src/signal_handlers.c
Labels: bug, Task

#26 21 builtin exit
  Makefile
  includes/minishell.h
  src/command_executor.c
  src/exit.c
Labels: Task

#28 Export builtin + Ctrl - D treatment
  Makefile
  includes/minishell.h
  src/build_env.c
  src/command_executor.c
  src/exit.c
  src/export.c
  src/main.c
Labels: enhancement, Task

#29 Unset builtin
  Makefile
  includes/minishell.h
  minishell
  src/command_executor.c
  src/export.c
  src/main.c
  src/unset.c
Labels: Task

#30 18 builtin cd
  Makefile
  includes/minishell.h
  src/cd.c
  src/command_executor.c
Labels: Task
