Repository speedshell/minishell, pull requests merged in 2023-01, with the labels that each got.

#39 38 bug echo printando nulo e não reconhecendo flag
  minishell
  src/echo.c
Labels: bug

#44 43 a norminette contra ataca
  Makefile
  includes/minishell.h
  src/cd.c
  src/command_loader.c
  src/env.c
  src/error_handler.c
  src/exit.c
  src/interpreter.c
  src/kludge.c
  src/main.c
  src/parser.c
  src/parser_rules.c
  src/pwd.c
  src/unset.c
Labels: enhancement

#48 47 bug melhorias em unset
  src/unset.c
Labels: bug, enhancement

#50 46 bug consertando export
  src/export.c
Labels: bug

#51 Expand Variable e exclusão da gambiarra
  Makefile
  includes/minishell.h
  src/expander.c
  src/export.c
  src/kludge.c
  src/main.c
Labels: enhancement

#52 49 pipex
  Makefile
  includes/minishell.h
  src/command_executor.c
  src/interpreter.c
  src/parser.c
  src/pipes.c
Labels: Task

#54 53 bug conectar quote resolverc e expanderc com o código
  Makefile
  includes/minishell.h
  src/expander.c
  src/expander_utils.c
  src/interpreter.c
  src/lexer.c
Labels: enhancement

#58 57 error codes + atualização da variável $
  Makefile
  includes/minishell.h
  src/error.c
  src/expander.c
  src/expander_utils.c
  src/lexer.c
  src/main.c
  src/pipes.c
  src/unset.c
Labels: enhancement

#61 Fix builtin invocation
  src/command_executor.c
Labels: bug

#63 Builtins erros - CD e ECHO
  includes/minishell.h
  src/cd.c
  src/echo.c
  src/error.c
  src/expander.c
  src/main.c
Labels: bug

#65 56 redirection e here doc
  Makefile
  includes/minishell.h
  src/cleaner.c
  src/command_executor.c
  src/command_pathfinder.c
  src/expander.c
  src/here_doc.c
  src/interpreter.c
  src/interpreter_utils.c
  src/lexer.c
  src/main.c
  src/parser.c
  src/pipes.c
  src/quote_resolver.c
  src/redirections.c
Labels: enhancement

#68 Error check dos builtins
  includes/minishell.h
  src/command_executor.c
  src/env.c
  src/exit.c
  src/export.c
  src/interpreter.c
Labels: bug, enhancement

#69 66 centralizar os vários mallocs da aplicação em uma struct
  Makefile
  includes/minishell.h
  src/cleaner.c
  src/command_builder.c
  src/command_executor.c
  src/exit.c
  src/export.c
  src/interpreter.c
  src/interpreter_utils.c
  src/lexer.c
  src/main.c
  src/unset.c
Labels: bug, enhancement

#73 now is_builtin checks both for equality and size of command string
  src/command_executor.c
Labels: bug

#74 70 código de retorno dos builtins e programas externos
  Makefile
  includes/minishell.h
  src/command_builder.c
  src/command_executor.c
  src/command_pathfinder.c
  src/error.c
  src/error_handler.c
  src/exit.c
  src/interpreter.c
  src/main.c
  src/parser.c
  src/parser_rules.c
  src/redirections.c
  src/redirections2.c
  src/signal_handlers.c
Labels: enhancement

#75 Add quote closing check and error message
  includes/minishell.h
  src/error_handler.c
  src/parser_rules.c
Labels: enhancement

#77 76 here doc durante tokenização
  Makefile
  includes/libft/libft.h
  includes/minishell.h
  src/cleaner.c
  src/command_builder.c
  src/command_executor.c
  src/command_pathfinder.c
  src/error_handler.c
  src/expander.c
  src/export.c
  src/here_doc.c
  src/interpreter.c
  src/interpreter_utils.c
  src/main.c
  src/name_generator.c
  src/parser_rules.c
  src/parser_rules2.c
  src/pid_list.c
  src/quote_resolver.c
  src/signal_handlers.c
Labels: bug, enhancement
